.PHONY : ALL test
ALL: 
	gcc -o helloworld helloworld.c
	gcc -o shell csapp.c shellex.c 
	gcc -o echo echo.c	
test:
	gcc -o test test.c

clean:
	rm -rf shell echo test helloworld


gcc -o job_test job_test.c job.c


gcc -o main job.c signal.c env.c csapp.c builtin.c main.c